- hosts: localhost
  vars:
    http_port: 80
    domain: buzut.fr
  tasks:
    - name:  install apache2
      apt:
          name: apache2
          state: present
          update_cache: yes
          force: yes
      notify:
        - start_apache
    - name: enable rewrite module
      apache2_module:
        name: rewrite
        state: present
    - name: Apache config file
      template:
         src: templates/vhost.conf
         dest: /etc/apache2/sites-available/buzut.conf
    - name: a2site
      command: /bin/ls /etc/apache2/sites-enabled/
      register: vhosts
    - name: a2site2
      command:  a2dissite "{{ item }}"
      with_items:
         - "{{ vhosts.stdout_lines }}"  
  handlers:
  - name: start_apache
    service:
      name: apache2
      state: started
